name: CI

on:
  push:
    paths:
      - '**'
      - '!**.md'
      - '!.github/**'
      - '.github/workflows/build_push.yml'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Prepare signing key
        run: echo ${{ secrets.SIGNING_KEY }} | base64 -d > signingkey.jks

      - name: Build extensions
        env:
          ALIAS: ${{ secrets.ALIAS }}
          KEY_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: ./gradlew -p src assembleRelease

      - name: Upload APKs
        uses: actions/upload-artifact@v4
        with:
          path: "**/*.apk"
          retention-days: 1

      - name: Clean up CI files
        run: rm signingkey.jks

# cwd
# - apk-artifacts/
# - main
#   - .github
#     - scripts/
# - repo
#   - apk/
#   - icon/
#   - index.json
#   - index.json.min
#   - repo.json
  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download APKs
        uses: actions/download-artifact@v4
        with:
          path: ./apk-artifacts

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
          path: main

      - name: Checkout repo branch
        uses: actions/checkout@v4
        with:
          ref: repo
          path: repo

      - name: Move APKs
        run: python ./main/.github/scripts/move-apks.py

      - name: Download and Run Inspector
        run: |
          INSPECTOR_LINK="$(curl -s "https://api.github.com/repos/keiyoushi/extensions-inspector/releases/tags/v1.4.7" | jq -r '.assets[0].browser_download_url')"
          curl -L "$INSPECTOR_LINK" -o ./Inspector.jar
          java -jar ./Inspector.jar "repo/apk" "output.json" "tmp"

      - name: Print output
        run: cat output.json

      - name: Create repo
        run: python ./main/.github/scripts/create-repo.py

      - name: Print index
        run: |
          cat ./repo/repo.json
          cat ./repo/index.json
          cat ./repo/index.json.min

      - name: Tree
        run: tree
