name: CI

on:
  push:
    paths:
      - '**'
      - '!**.md'
      - '!.github/**'
      - '.github/workflows/build_push.yml'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v3
